### PR TITLE
0.3 Vita release

### PR DESCRIPTION
**Pull request by 01y**
Fixes https://github.com/01y/bstone-vita/issues/2 and https://github.com/bibendovsky/bstone/issues/170; Improvements to controls on Vita

### CODE REVIEW

**Comment by bibendovsky** [comment]
What about README.md and README-PSVITA.md?
They are equal.

**Comment by 01y** [comment]
I wanted to keep the port's readme file's name as "README.md", so that it would be displayed by default on the project's github.com landing page. I am not 100% sure, but I believe the following line https://github.com/bibendovsky/bstone/blob/develop/.gitattributes#L3 which you accepted in my last PR will prevent overwriting the README.md file again. At least it prevents the reverse from happening when I merge in changes from upstream.

**Comment by bibendovsky** [comment]
I reverted changes for README.md and .gitattributes.

**Comment by 01y** [comment]
Not sure if .gitattributes affects the behaviour of Github.com when performing merges, but it had seemed to work well on the commandline (namely, it's purpose was to prevent the two versions of README.md from overwriting one another in either direction).

**Pull request merged**
