### PR TITLE
minor changes/cleanup to icon assets, CMakelists, docs

### PR DESCRIPTION
**Pull request by 01y**

### CODE REVIEW

**Comment by bibendovsky** [comment]
@01y, are you planning on finishing the PR?

**Comment by 01y** [comment]
Yes, sorry about that. Was on a bit of a hiatus for a while. Will attempt to get this working with the current version.

**Comment by 01y** [comment]
I'd like to do a little more testing and perform a couple more changes before merging, if that's alright. Thanks for your patience. A couple of issues affecting the Vita version got fixed by your recent commits, which is also much appreciated.

**Comment by 01y** [comment]
@bibendovsky,

So I think I've got my changes down to a bare minimum, but there is still one big problem which has persisted through the past few versions, namely the issue described here: https://github.com/01y/bstone-vita/issues/2

So far I have not been able to reproduce this on non-Vita platforms, so maybe this is caused by a problem with the VitaSDK libraries. Any ideas as to what might be behind this?

**Comment by bibendovsky** [comment]
> So far I have not been able to reproduce this on non-Vita platforms, so maybe this is caused by a problem with the VitaSDK libraries. Any ideas as to what might be behind this?

Try to figure out what part of the port may cause the crash.
Start with audio mixer's callback (AudioMixer::Impl::callback_proxy).
For example, add try/catch and log the exception. You may also to add exception handler for unhandled exceptions in the entry point (main, 3d_main.cpp).

**Pull request merged**
